[package]
name = "FirstRustProject"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "app"
path = "src/app.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"